<a href="https://colab.research.google.com/github/M1nseokSong/data_science_study/blob/main/index_column_change.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

liverpool_df = pd.read_csv('liverpool.csv', index_col=0)
liverpool_df

                position  born  number nationality
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [7]:
liverpool_df.rename(columns={'position': 'Posi'}, inplace=True)
liverpool_df.index.name = 'Player Name'
liverpool_df

                Posi  born  number nationality
Player Name
Roberto Firmino   FW  1991   no. 9      Brazil
Sadio Mane        FW  1992  no. 10     Senegal
Mohamed Salah     FW  1992  no. 11       Egypt
Joe Gomez         DF  1997  no. 12     England
Alisson Becker    GK  1992  no. 13      Brazil

In [11]:
liverpool_df.index
liverpool_df['Player Name'] = liverpool_df.index
liverpool_df.set_index('number', inplace=True)
liverpool_df

       Posi  born nationality      Player Name
number
no. 9    FW  1991      Brazil  Roberto Firmino
no. 10   FW  1992     Senegal       Sadio Mane
no. 11   FW  1992       Egypt    Mohamed Salah
no. 12   DF  1997     England        Joe Gomez
no. 13   GK  1992      Brazil   Alisson Becker